### PR TITLE
feat(AC check): Add endpoint to get most recent event of a body

### PR DESCRIPTION
**Pull request by LeonVreling**
Needed for functioning of https://github.com/AEGEE/frontend/pull/2036

### CODE REVIEW

**Comment by WikiRik** [comment]
Before I forget; we do not know right now which events count for the Antenna Criteria (and even that changes depending on if you want to upgrade to an antenna or want to remain an antenna)

Upgrade to an antenna; "Have organised a European event, AEGEE event or AEGEE-Europe event according to
the Event Rules in the past two years."
Remaining an antenna; "Have organised a European event or Summer University at least once every two years."

**Comment by WikiRik** [comment]
In general I'm okay with merging this (after a positive review), but it cannot be used as AC check yet. The new proposal from EQAC et al also excludes some events mentioned on MyAEGEE to count as fulfilling AC. Maybe we should add an additional field and check for the most recent one of that instead

**Comment by LeonVreling** [comment]
Yes agreed, this will most likely need to change if the EQAC proposal is accepted (which would also be good for the implementation, since then the criteria are merged that you mentioned above)

**Comment by WikiRik** [comment]
If I read the draft correctly, the new proposal still does not mention that all MyAEGEE events (that fall under this microservice) are eligible for the AC. So we still need some additional logic here I think. Easiest is to add a checkbox mentioning that it counts as European Event. But do note that as definitions change, we will have more logic there so that's going to be fun

**Comment by LeonVreling** [comment]
@WikiRik I believe all events from this microservice are now eligible, could you please check

**Review by WikiRik — APPROVED** [review]

**Pull request merged**
